### ISSUE TITLE
dockerがたまに止まる

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg-online-demo#26]
ほっておくといつの間にか死んでる

**Comment by shinsuke-mat** [comment]
workaround: docker run時の--restart

**Comment by shinsuke-mat** [comment]
死ぬ瞬間のログを捕まえたので残しておく


```
2022-04-25T09:10:33.401849972Z [08e967fc35dd665a5a752f5499f856dc] accept submission
2022-04-25T09:10:33.402811944Z POST /api/submission 200 0.927 ms - 74
2022-04-25T09:10:33.415136545Z [08e967fc35dd665a5a752f5499f856dc] connected websocket
2022-04-25T09:10:33.417583017Z events.js:291
2022-04-25T09:10:33.417602326Z       throw er; // Unhandled 'error' event
2022-04-25T09:10:33.417607182Z       ^
2022-04-25T09:10:33.417610445Z
2022-04-25T09:10:33.417613338Z Error: spawn java ENOENT
2022-04-25T09:10:33.417616420Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
2022-04-25T09:10:33.417619597Z     at onErrorNT (internal/child_process.js:470:16)
2022-04-25T09:10:33.417622928Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-04-25T09:10:33.417626047Z Emitted 'error' event on ChildProcess instance at:
2022-04-25T09:10:33.417629178Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
2022-04-25T09:10:33.417643708Z     at onErrorNT (internal/child_process.js:470:16)
2022-04-25T09:10:33.417645718Z     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2022-04-25T09:10:33.417647663Z   errno: 'ENOENT',
2022-04-25T09:10:33.417649527Z   code: 'ENOENT',
2022-04-25T09:10:33.417651444Z   syscall: 'spawn java',
2022-04-25T09:10:33.417653195Z   path: 'java',
2022-04-25T09:10:33.417654898Z   spawnargs: [
2022-04-25T09:10:33.417656599Z     '-jar',
2022-04-25T09:10:33.417658287Z     '/kdemo/bin/kgp.jar',
2022-04-25T09:10:33.417660099Z     '-r',
2022-04-25T09:10:33.417661897Z     './',
2022-04-25T09:10:33.417663623Z     '-s',
2022-04-25T09:10:33.417665346Z     'src/main',
2022-04-25T09:10:33.417667125Z     '-t',
2022-04-25T09:10:33.417668805Z     'src/test',
2022-04-25T09:10:33.417670514Z     '--max-generation',
2022-04-25T09:10:33.417672232Z     '1000',
2022-04-25T09:10:33.417673984Z     '--time-limit',
2022-04-25T09:10:33.417675866Z     '300'
2022-04-25T09:10:33.417677704Z   ]
2022-04-25T09:10:33.417679496Z }
2022-04-25T09:10:33.428788186Z npm ERR! code ELIFECYCLE
2022-04-25T09:10:33.429221682Z npm ERR! errno 1
2022-04-25T09:10:33.432006712Z npm ERR! kdemo@0.0.0 start: `node ./bin/www`
2022-04-25T09:10:33.432273124Z npm ERR! Exit status 1
2022-04-25T09:10:33.432469067Z npm ERR!
2022-04-25T09:10:33.432613798Z npm ERR! Failed at the kdemo@0.0.0 start script.
2022-04-25T09:10:33.432846730Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-04-25T09:10:33.457836884Z
2022-04-25T09:10:33.458064005Z npm ERR! A complete log of this run can be found in:
2022-04-25T09:10:33.458206822Z npm ERR!     /root/.npm/_logs/2022-04-25T09_10_33_433Z-debug.log
2022-04-25T09:10:34.724747555Z
```
